name: CI
on: [push, pull_request]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pytest and deps
        run: |
          pip install --upgrade pip
          pip install pytest pytest-spec pytest-describe pytest-mock
      - name: Run pytest
        run: pytest --spec

  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          # Install Chromium and ChromeDriver
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install behave and behave-webdriver
        run: |
          pip install --upgrade pip
          pip install behave behave-webdriver selenium

      - name: Check versions
        run: |
          chromium-browser --version
          chromedriver --version
          python -m pip show behave behave-webdriver selenium

      - name: Run functional tests
        run: behave