name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-describe pytest-spec pytest-mock
      - name: Run unit tests
        run: pytest --spec

  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      
      - name: Install behave
        run: pip install behave behave-webdriver

      - name: Run functional tests
        run: behave